free = $(".free[data-date='<%= @block.date %>'][data-hour='<%= @block.hour %>']")
free_alert = free.find('.alert')
free_alert.removeClass('alert-success')
free_alert.addClass('alert-disabled')
free_alert.html('Нет приема')
free.data('id','<%= @block.id %>')
free.removeClass('free')
free.addClass('blocked')
free_alert.show()
